
services:

  blogAppDB-mongo:
    image: mongo
    container_name: blogAppDB-mongo
    restart: always
    command: "mongod --port 27017"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: DevMeley
      MONGO_INITDB_ROOT_PASSWORD: MHwHUDm7RLxfBq5r
      MONGO_INITDB_ROOT_DATABASE: admin 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: DevMeley
      ME_CONFIG_MONGODB_ADMINPASSWORD: MHwHUDm7RLxfBq5r
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@blogAppDB-mongo:27017/
      ME_CONFIG_MONGODB_URL: mongodb+srv://DevMeley:UtQI0W1X9WkbOxei@blog-app-db.bxgxcz7.mongodb.net/
      ME_CONFIG_BASICAUTH: false
