
services:

  blogAppDB-mongo:
    image: mongo
    container_name: blogAppDB-mongo
    restart: always
    command: "mongod --port 27017"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: admin 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: DevMeley
      ME_CONFIG_MONGODB_ADMINPASSWORD: DevMeley
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@blogAppDB-mongo:27017/
      ME_CONFIG_MONGODB_URL: mongodb+srv://DevMeley:DevMeley@blog-app-db.bxgxcz7.mongodb.net/?retryWrites=true&w=majority&appName=Blog-App-DB
      ME_CONFIG_BASICAUTH: false
